export const PAGE_SIZE = 10;

export const CONTACTS = [
  {
    id: 1,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 2,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 3,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 4,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 5,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 6,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 7,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 8,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 9,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 10,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 11,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 12,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 13,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 14,
    firstName: "Jacob",
    lastName: "Jones",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 15,
    firstName: "Ronald",
    lastName: "Richards",
    role: { label: "Owner", value: 1 },
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
];
