export const PAGE_SIZE = 10;

export const CONTACTS = [
  {
    id: 1,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 2,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 3,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 4,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 5,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 6,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 7,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 8,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 9,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 10,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 11,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 12,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 13,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 14,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 15,
    name: "Ronald Richards",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
  {
    id: 2,
    name: "Jacob Jones",
    role: "Owner",
    email: "albert@borer.com",
    created_at: "Feb, 5, 2021",
  },
];
